### ISSUE TITLE
Per environment and region hooks

### ISSUE THREAD

**Issue by phylake** [adobe-platform/porter#108]
``` yaml
hooks:
  pre_promote:
  - dockerfile: pre_promote
    environment:
      CONFIG:

environments:
- name: stage
  hooks:
    pre_promote:
    - dockerfile: pre_promote
      environment:
        CONFIG:
  regions:
  - name: us-west-2
    hooks:
      pre_promote:
      - dockerfile: pre_promote
        environment:
          CONFIG: some_value
```
